/**
 * generated by Xtext 2.16.0
 */
package de.validas.spedit.naturalLang.impl;

import de.validas.spedit.naturalLang.ChapterAlpha;
import de.validas.spedit.naturalLang.NaturalLangPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Chapter Alpha</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ChapterAlphaImpl extends NoNElementX2Impl implements ChapterAlpha
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ChapterAlphaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return NaturalLangPackage.Literals.CHAPTER_ALPHA;
  }

} //ChapterAlphaImpl
