/**
 * generated by Xtext 2.16.0
 */
package de.validas.spedit.naturalLang.impl;

import de.validas.spedit.naturalLang.ExtBracketSentence;
import de.validas.spedit.naturalLang.NaturalLangPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Ext Bracket Sentence</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExtBracketSentenceImpl extends BracketSentenceImpl implements ExtBracketSentence
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExtBracketSentenceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return NaturalLangPackage.Literals.EXT_BRACKET_SENTENCE;
  }

} //ExtBracketSentenceImpl
