/**
 * generated by Xtext 2.16.0
 */
package de.validas.spedit.naturalLang.impl;

import de.validas.spedit.naturalLang.FreeSentence;
import de.validas.spedit.naturalLang.NaturalLangPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Free Sentence</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class FreeSentenceImpl extends MinimalEObjectImpl.Container implements FreeSentence
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FreeSentenceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return NaturalLangPackage.Literals.FREE_SENTENCE;
  }

} //FreeSentenceImpl
