/**
 * generated by Xtext 2.16.0
 */
package de.validas.spedit.naturalLang.impl;

import de.validas.spedit.naturalLang.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class NaturalLangFactoryImpl extends EFactoryImpl implements NaturalLangFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static NaturalLangFactory init()
  {
    try
    {
      NaturalLangFactory theNaturalLangFactory = (NaturalLangFactory)EPackage.Registry.INSTANCE.getEFactory(NaturalLangPackage.eNS_URI);
      if (theNaturalLangFactory != null)
      {
        return theNaturalLangFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new NaturalLangFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NaturalLangFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case NaturalLangPackage.MODEL: return createModel();
      case NaturalLangPackage.SENTENCE_TYPE: return createSentenceType();
      case NaturalLangPackage.PARAGRAPH_BLOCK: return createParagraphBlock();
      case NaturalLangPackage.BLOCK_ELEMENT: return createBlockElement();
      case NaturalLangPackage.FOOT_NOTE: return createFootNote();
      case NaturalLangPackage.TABLE_LINE: return createTableLine();
      case NaturalLangPackage.TABLE_BORDER: return createTableBorder();
      case NaturalLangPackage.TABLE_ROW: return createTableRow();
      case NaturalLangPackage.TABLE_COLUMN_SEPARATOR: return createTableColumnSeparator();
      case NaturalLangPackage.TABLE: return createTable();
      case NaturalLangPackage.LINE_SENTENCE_CHAIN: return createLineSentenceChain();
      case NaturalLangPackage.SENTENCE_CHAIN: return createSentenceChain();
      case NaturalLangPackage.SENTENCE_CHAIN_X: return createSentenceChainX();
      case NaturalLangPackage.SENTENCE: return createSentence();
      case NaturalLangPackage.LINE_SENTENCE: return createLineSentence();
      case NaturalLangPackage.FREE_SENTENCE: return createFreeSentence();
      case NaturalLangPackage.SENTENCE_X: return createSentenceX();
      case NaturalLangPackage.LIST_SENTENCE: return createListSentence();
      case NaturalLangPackage.CHAPTER_SENTENCE: return createChapterSentence();
      case NaturalLangPackage.SUB_SENTENCE: return createSubSentence();
      case NaturalLangPackage.TRAIL_SUB_SENTENCE: return createTrailSubSentence();
      case NaturalLangPackage.FREE_SUB_SENTENCE: return createFreeSubSentence();
      case NaturalLangPackage.LINE_SUB_SENTENCE: return createLineSubSentence();
      case NaturalLangPackage.NO_NELEMENT: return createNoNElement();
      case NaturalLangPackage.BRACKETS: return createBrackets();
      case NaturalLangPackage.NO_NELEMENT_X: return createNoNElementX();
      case NaturalLangPackage.NO_NELEMENT_X2: return createNoNElementX2();
      case NaturalLangPackage.ELEMENTS: return createElements();
      case NaturalLangPackage.ALL_ELEMENTS: return createAllElements();
      case NaturalLangPackage.BRACKET_SENTENCE: return createBracketSentence();
      case NaturalLangPackage.WORD: return createWord();
      case NaturalLangPackage.WORD_SHORT: return createWordShort();
      case NaturalLangPackage.IT_WORD: return createItWord();
      case NaturalLangPackage.QUOTE: return createQuote();
      case NaturalLangPackage.UNIT: return createUnit();
      case NaturalLangPackage.SIMPLE_UNIT: return createSimpleUnit();
      case NaturalLangPackage.CHAPTER_UNIT_HI: return createChapter_Unit_HI();
      case NaturalLangPackage.CHAPTER_UNIT_LOW: return createChapter_Unit_Low();
      case NaturalLangPackage.HASH_NUMBER: return createHashNumber();
      case NaturalLangPackage.CHAPTER_ALPHA: return createChapterAlpha();
      case NaturalLangPackage.SYMBOLS_X: return createSymbolsX();
      case NaturalLangPackage.SYMBOLS: return createSymbols();
      case NaturalLangPackage.SHORTCUT_GEN: return createShortcutGen();
      case NaturalLangPackage.SHORTCUT_LIB: return createShortcutLib();
      case NaturalLangPackage.SHORT_CUT: return createShortCut();
      case NaturalLangPackage.IGNORED_TEXT: return createIgnoredText();
      case NaturalLangPackage.URL_ADRESS: return createUrlAdress();
      case NaturalLangPackage.EMAIL_AT: return createEmailAT();
      case NaturalLangPackage.MAIL_ADRESS: return createMailAdress();
      case NaturalLangPackage.FORMULA: return createFormula();
      case NaturalLangPackage.ARRAY: return createArray();
      case NaturalLangPackage.NEW_LINE: return createNew_Line();
      case NaturalLangPackage.EXT_BRACKET_SENTENCE: return createExtBracketSentence();
      case NaturalLangPackage.ESTRING: return createEString();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SentenceType createSentenceType()
  {
    SentenceTypeImpl sentenceType = new SentenceTypeImpl();
    return sentenceType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ParagraphBlock createParagraphBlock()
  {
    ParagraphBlockImpl paragraphBlock = new ParagraphBlockImpl();
    return paragraphBlock;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BlockElement createBlockElement()
  {
    BlockElementImpl blockElement = new BlockElementImpl();
    return blockElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FootNote createFootNote()
  {
    FootNoteImpl footNote = new FootNoteImpl();
    return footNote;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TableLine createTableLine()
  {
    TableLineImpl tableLine = new TableLineImpl();
    return tableLine;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TableBorder createTableBorder()
  {
    TableBorderImpl tableBorder = new TableBorderImpl();
    return tableBorder;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TableRow createTableRow()
  {
    TableRowImpl tableRow = new TableRowImpl();
    return tableRow;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TableColumnSeparator createTableColumnSeparator()
  {
    TableColumnSeparatorImpl tableColumnSeparator = new TableColumnSeparatorImpl();
    return tableColumnSeparator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Table createTable()
  {
    TableImpl table = new TableImpl();
    return table;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LineSentenceChain createLineSentenceChain()
  {
    LineSentenceChainImpl lineSentenceChain = new LineSentenceChainImpl();
    return lineSentenceChain;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SentenceChain createSentenceChain()
  {
    SentenceChainImpl sentenceChain = new SentenceChainImpl();
    return sentenceChain;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SentenceChainX createSentenceChainX()
  {
    SentenceChainXImpl sentenceChainX = new SentenceChainXImpl();
    return sentenceChainX;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Sentence createSentence()
  {
    SentenceImpl sentence = new SentenceImpl();
    return sentence;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LineSentence createLineSentence()
  {
    LineSentenceImpl lineSentence = new LineSentenceImpl();
    return lineSentence;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FreeSentence createFreeSentence()
  {
    FreeSentenceImpl freeSentence = new FreeSentenceImpl();
    return freeSentence;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SentenceX createSentenceX()
  {
    SentenceXImpl sentenceX = new SentenceXImpl();
    return sentenceX;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ListSentence createListSentence()
  {
    ListSentenceImpl listSentence = new ListSentenceImpl();
    return listSentence;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ChapterSentence createChapterSentence()
  {
    ChapterSentenceImpl chapterSentence = new ChapterSentenceImpl();
    return chapterSentence;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SubSentence createSubSentence()
  {
    SubSentenceImpl subSentence = new SubSentenceImpl();
    return subSentence;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TrailSubSentence createTrailSubSentence()
  {
    TrailSubSentenceImpl trailSubSentence = new TrailSubSentenceImpl();
    return trailSubSentence;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FreeSubSentence createFreeSubSentence()
  {
    FreeSubSentenceImpl freeSubSentence = new FreeSubSentenceImpl();
    return freeSubSentence;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LineSubSentence createLineSubSentence()
  {
    LineSubSentenceImpl lineSubSentence = new LineSubSentenceImpl();
    return lineSubSentence;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NoNElement createNoNElement()
  {
    NoNElementImpl noNElement = new NoNElementImpl();
    return noNElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Brackets createBrackets()
  {
    BracketsImpl brackets = new BracketsImpl();
    return brackets;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NoNElementX createNoNElementX()
  {
    NoNElementXImpl noNElementX = new NoNElementXImpl();
    return noNElementX;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NoNElementX2 createNoNElementX2()
  {
    NoNElementX2Impl noNElementX2 = new NoNElementX2Impl();
    return noNElementX2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Elements createElements()
  {
    ElementsImpl elements = new ElementsImpl();
    return elements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AllElements createAllElements()
  {
    AllElementsImpl allElements = new AllElementsImpl();
    return allElements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BracketSentence createBracketSentence()
  {
    BracketSentenceImpl bracketSentence = new BracketSentenceImpl();
    return bracketSentence;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Word createWord()
  {
    WordImpl word = new WordImpl();
    return word;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public WordShort createWordShort()
  {
    WordShortImpl wordShort = new WordShortImpl();
    return wordShort;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ItWord createItWord()
  {
    ItWordImpl itWord = new ItWordImpl();
    return itWord;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Quote createQuote()
  {
    QuoteImpl quote = new QuoteImpl();
    return quote;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Unit createUnit()
  {
    UnitImpl unit = new UnitImpl();
    return unit;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SimpleUnit createSimpleUnit()
  {
    SimpleUnitImpl simpleUnit = new SimpleUnitImpl();
    return simpleUnit;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Chapter_Unit_HI createChapter_Unit_HI()
  {
    Chapter_Unit_HIImpl chapter_Unit_HI = new Chapter_Unit_HIImpl();
    return chapter_Unit_HI;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Chapter_Unit_Low createChapter_Unit_Low()
  {
    Chapter_Unit_LowImpl chapter_Unit_Low = new Chapter_Unit_LowImpl();
    return chapter_Unit_Low;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public HashNumber createHashNumber()
  {
    HashNumberImpl hashNumber = new HashNumberImpl();
    return hashNumber;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ChapterAlpha createChapterAlpha()
  {
    ChapterAlphaImpl chapterAlpha = new ChapterAlphaImpl();
    return chapterAlpha;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SymbolsX createSymbolsX()
  {
    SymbolsXImpl symbolsX = new SymbolsXImpl();
    return symbolsX;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Symbols createSymbols()
  {
    SymbolsImpl symbols = new SymbolsImpl();
    return symbols;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ShortcutGen createShortcutGen()
  {
    ShortcutGenImpl shortcutGen = new ShortcutGenImpl();
    return shortcutGen;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ShortcutLib createShortcutLib()
  {
    ShortcutLibImpl shortcutLib = new ShortcutLibImpl();
    return shortcutLib;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ShortCut createShortCut()
  {
    ShortCutImpl shortCut = new ShortCutImpl();
    return shortCut;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IgnoredText createIgnoredText()
  {
    IgnoredTextImpl ignoredText = new IgnoredTextImpl();
    return ignoredText;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public UrlAdress createUrlAdress()
  {
    UrlAdressImpl urlAdress = new UrlAdressImpl();
    return urlAdress;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EmailAT createEmailAT()
  {
    EmailATImpl emailAT = new EmailATImpl();
    return emailAT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MailAdress createMailAdress()
  {
    MailAdressImpl mailAdress = new MailAdressImpl();
    return mailAdress;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Formula createFormula()
  {
    FormulaImpl formula = new FormulaImpl();
    return formula;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Array createArray()
  {
    ArrayImpl array = new ArrayImpl();
    return array;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public New_Line createNew_Line()
  {
    New_LineImpl new_Line = new New_LineImpl();
    return new_Line;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ExtBracketSentence createExtBracketSentence()
  {
    ExtBracketSentenceImpl extBracketSentence = new ExtBracketSentenceImpl();
    return extBracketSentence;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EString createEString()
  {
    EStringImpl eString = new EStringImpl();
    return eString;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NaturalLangPackage getNaturalLangPackage()
  {
    return (NaturalLangPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static NaturalLangPackage getPackage()
  {
    return NaturalLangPackage.eINSTANCE;
  }

} //NaturalLangFactoryImpl
