/*
 * generated by Xtext 2.16.0
 */
package de.validas.spedit.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class NaturalLangWebModule extends AbstractNaturalLangWebModule {
}
