/*
 * generated by Xtext 2.16.0
 */
package de.validas.spedit.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class NaturalLangAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("de/validas/spedit/parser/antlr/internal/InternalNaturalLang.tokens");
	}
}
