/**
 * generated by Xtext 2.16.0
 */
package de.validas.spedit.naturalLang;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bracket Sentence</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.validas.spedit.naturalLang.BracketSentence#getOpen <em>Open</em>}</li>
 *   <li>{@link de.validas.spedit.naturalLang.BracketSentence#getBrackedSentences <em>Bracked Sentences</em>}</li>
 *   <li>{@link de.validas.spedit.naturalLang.BracketSentence#getSeparator <em>Separator</em>}</li>
 *   <li>{@link de.validas.spedit.naturalLang.BracketSentence#getClose <em>Close</em>}</li>
 * </ul>
 *
 * @see de.validas.spedit.naturalLang.NaturalLangPackage#getBracketSentence()
 * @model
 * @generated
 */
public interface BracketSentence extends Brackets
{
  /**
   * Returns the value of the '<em><b>Open</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Open</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Open</em>' attribute.
   * @see #setOpen(String)
   * @see de.validas.spedit.naturalLang.NaturalLangPackage#getBracketSentence_Open()
   * @model
   * @generated
   */
  String getOpen();

  /**
   * Sets the value of the '{@link de.validas.spedit.naturalLang.BracketSentence#getOpen <em>Open</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Open</em>' attribute.
   * @see #getOpen()
   * @generated
   */
  void setOpen(String value);

  /**
   * Returns the value of the '<em><b>Bracked Sentences</b></em>' containment reference list.
   * The list contents are of type {@link de.validas.spedit.naturalLang.FreeSentence}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bracked Sentences</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bracked Sentences</em>' containment reference list.
   * @see de.validas.spedit.naturalLang.NaturalLangPackage#getBracketSentence_BrackedSentences()
   * @model containment="true"
   * @generated
   */
  EList<FreeSentence> getBrackedSentences();

  /**
   * Returns the value of the '<em><b>Separator</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Separator</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Separator</em>' attribute list.
   * @see de.validas.spedit.naturalLang.NaturalLangPackage#getBracketSentence_Separator()
   * @model unique="false"
   * @generated
   */
  EList<String> getSeparator();

  /**
   * Returns the value of the '<em><b>Close</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Close</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Close</em>' attribute.
   * @see #setClose(String)
   * @see de.validas.spedit.naturalLang.NaturalLangPackage#getBracketSentence_Close()
   * @model
   * @generated
   */
  String getClose();

  /**
   * Sets the value of the '{@link de.validas.spedit.naturalLang.BracketSentence#getClose <em>Close</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Close</em>' attribute.
   * @see #getClose()
   * @generated
   */
  void setClose(String value);

} // BracketSentence
