/**
 * generated by Xtext 2.16.0
 */
package de.validas.spedit.naturalLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Chapter Unit Low</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.validas.spedit.naturalLang.NaturalLangPackage#getChapter_Unit_Low()
 * @model
 * @generated
 */
public interface Chapter_Unit_Low extends EObject
{
} // Chapter_Unit_Low
