/**
 * generated by Xtext 2.16.0
 */
package de.validas.spedit.naturalLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Free Sentence</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.validas.spedit.naturalLang.NaturalLangPackage#getFreeSentence()
 * @model
 * @generated
 */
public interface FreeSentence extends EObject
{
} // FreeSentence
