/**
 * generated by Xtext 2.16.0
 */
package de.validas.spedit.naturalLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Hash Number</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.validas.spedit.naturalLang.NaturalLangPackage#getHashNumber()
 * @model
 * @generated
 */
public interface HashNumber extends NoNElement
{
} // HashNumber
