/**
 * generated by Xtext 2.16.0
 */
package de.validas.spedit.naturalLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>List Sentence</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.validas.spedit.naturalLang.ListSentence#getListpoint <em>Listpoint</em>}</li>
 *   <li>{@link de.validas.spedit.naturalLang.ListSentence#getSentenceChain <em>Sentence Chain</em>}</li>
 * </ul>
 *
 * @see de.validas.spedit.naturalLang.NaturalLangPackage#getListSentence()
 * @model
 * @generated
 */
public interface ListSentence extends BlockElement
{
  /**
   * Returns the value of the '<em><b>Listpoint</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Listpoint</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Listpoint</em>' attribute.
   * @see #setListpoint(String)
   * @see de.validas.spedit.naturalLang.NaturalLangPackage#getListSentence_Listpoint()
   * @model
   * @generated
   */
  String getListpoint();

  /**
   * Sets the value of the '{@link de.validas.spedit.naturalLang.ListSentence#getListpoint <em>Listpoint</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Listpoint</em>' attribute.
   * @see #getListpoint()
   * @generated
   */
  void setListpoint(String value);

  /**
   * Returns the value of the '<em><b>Sentence Chain</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sentence Chain</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sentence Chain</em>' containment reference.
   * @see #setSentenceChain(SentenceChainX)
   * @see de.validas.spedit.naturalLang.NaturalLangPackage#getListSentence_SentenceChain()
   * @model containment="true"
   * @generated
   */
  SentenceChainX getSentenceChain();

  /**
   * Sets the value of the '{@link de.validas.spedit.naturalLang.ListSentence#getSentenceChain <em>Sentence Chain</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sentence Chain</em>' containment reference.
   * @see #getSentenceChain()
   * @generated
   */
  void setSentenceChain(SentenceChainX value);

} // ListSentence
