/**
 * generated by Xtext 2.16.0
 */
package de.validas.spedit.naturalLang;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see de.validas.spedit.naturalLang.NaturalLangPackage
 * @generated
 */
public interface NaturalLangFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  NaturalLangFactory eINSTANCE = de.validas.spedit.naturalLang.impl.NaturalLangFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Sentence Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sentence Type</em>'.
   * @generated
   */
  SentenceType createSentenceType();

  /**
   * Returns a new object of class '<em>Paragraph Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Paragraph Block</em>'.
   * @generated
   */
  ParagraphBlock createParagraphBlock();

  /**
   * Returns a new object of class '<em>Block Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Block Element</em>'.
   * @generated
   */
  BlockElement createBlockElement();

  /**
   * Returns a new object of class '<em>Foot Note</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Foot Note</em>'.
   * @generated
   */
  FootNote createFootNote();

  /**
   * Returns a new object of class '<em>Table Line</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Table Line</em>'.
   * @generated
   */
  TableLine createTableLine();

  /**
   * Returns a new object of class '<em>Table Border</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Table Border</em>'.
   * @generated
   */
  TableBorder createTableBorder();

  /**
   * Returns a new object of class '<em>Table Row</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Table Row</em>'.
   * @generated
   */
  TableRow createTableRow();

  /**
   * Returns a new object of class '<em>Table Column Separator</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Table Column Separator</em>'.
   * @generated
   */
  TableColumnSeparator createTableColumnSeparator();

  /**
   * Returns a new object of class '<em>Table</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Table</em>'.
   * @generated
   */
  Table createTable();

  /**
   * Returns a new object of class '<em>Line Sentence Chain</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Line Sentence Chain</em>'.
   * @generated
   */
  LineSentenceChain createLineSentenceChain();

  /**
   * Returns a new object of class '<em>Sentence Chain</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sentence Chain</em>'.
   * @generated
   */
  SentenceChain createSentenceChain();

  /**
   * Returns a new object of class '<em>Sentence Chain X</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sentence Chain X</em>'.
   * @generated
   */
  SentenceChainX createSentenceChainX();

  /**
   * Returns a new object of class '<em>Sentence</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sentence</em>'.
   * @generated
   */
  Sentence createSentence();

  /**
   * Returns a new object of class '<em>Line Sentence</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Line Sentence</em>'.
   * @generated
   */
  LineSentence createLineSentence();

  /**
   * Returns a new object of class '<em>Free Sentence</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Free Sentence</em>'.
   * @generated
   */
  FreeSentence createFreeSentence();

  /**
   * Returns a new object of class '<em>Sentence X</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sentence X</em>'.
   * @generated
   */
  SentenceX createSentenceX();

  /**
   * Returns a new object of class '<em>List Sentence</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>List Sentence</em>'.
   * @generated
   */
  ListSentence createListSentence();

  /**
   * Returns a new object of class '<em>Chapter Sentence</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Chapter Sentence</em>'.
   * @generated
   */
  ChapterSentence createChapterSentence();

  /**
   * Returns a new object of class '<em>Sub Sentence</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sub Sentence</em>'.
   * @generated
   */
  SubSentence createSubSentence();

  /**
   * Returns a new object of class '<em>Trail Sub Sentence</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Trail Sub Sentence</em>'.
   * @generated
   */
  TrailSubSentence createTrailSubSentence();

  /**
   * Returns a new object of class '<em>Free Sub Sentence</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Free Sub Sentence</em>'.
   * @generated
   */
  FreeSubSentence createFreeSubSentence();

  /**
   * Returns a new object of class '<em>Line Sub Sentence</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Line Sub Sentence</em>'.
   * @generated
   */
  LineSubSentence createLineSubSentence();

  /**
   * Returns a new object of class '<em>No NElement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>No NElement</em>'.
   * @generated
   */
  NoNElement createNoNElement();

  /**
   * Returns a new object of class '<em>Brackets</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Brackets</em>'.
   * @generated
   */
  Brackets createBrackets();

  /**
   * Returns a new object of class '<em>No NElement X</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>No NElement X</em>'.
   * @generated
   */
  NoNElementX createNoNElementX();

  /**
   * Returns a new object of class '<em>No NElement X2</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>No NElement X2</em>'.
   * @generated
   */
  NoNElementX2 createNoNElementX2();

  /**
   * Returns a new object of class '<em>Elements</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Elements</em>'.
   * @generated
   */
  Elements createElements();

  /**
   * Returns a new object of class '<em>All Elements</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>All Elements</em>'.
   * @generated
   */
  AllElements createAllElements();

  /**
   * Returns a new object of class '<em>Bracket Sentence</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bracket Sentence</em>'.
   * @generated
   */
  BracketSentence createBracketSentence();

  /**
   * Returns a new object of class '<em>Word</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Word</em>'.
   * @generated
   */
  Word createWord();

  /**
   * Returns a new object of class '<em>Word Short</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Word Short</em>'.
   * @generated
   */
  WordShort createWordShort();

  /**
   * Returns a new object of class '<em>It Word</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>It Word</em>'.
   * @generated
   */
  ItWord createItWord();

  /**
   * Returns a new object of class '<em>Quote</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Quote</em>'.
   * @generated
   */
  Quote createQuote();

  /**
   * Returns a new object of class '<em>Unit</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Unit</em>'.
   * @generated
   */
  Unit createUnit();

  /**
   * Returns a new object of class '<em>Simple Unit</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Simple Unit</em>'.
   * @generated
   */
  SimpleUnit createSimpleUnit();

  /**
   * Returns a new object of class '<em>Chapter Unit HI</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Chapter Unit HI</em>'.
   * @generated
   */
  Chapter_Unit_HI createChapter_Unit_HI();

  /**
   * Returns a new object of class '<em>Chapter Unit Low</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Chapter Unit Low</em>'.
   * @generated
   */
  Chapter_Unit_Low createChapter_Unit_Low();

  /**
   * Returns a new object of class '<em>Hash Number</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Hash Number</em>'.
   * @generated
   */
  HashNumber createHashNumber();

  /**
   * Returns a new object of class '<em>Chapter Alpha</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Chapter Alpha</em>'.
   * @generated
   */
  ChapterAlpha createChapterAlpha();

  /**
   * Returns a new object of class '<em>Symbols X</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Symbols X</em>'.
   * @generated
   */
  SymbolsX createSymbolsX();

  /**
   * Returns a new object of class '<em>Symbols</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Symbols</em>'.
   * @generated
   */
  Symbols createSymbols();

  /**
   * Returns a new object of class '<em>Shortcut Gen</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Shortcut Gen</em>'.
   * @generated
   */
  ShortcutGen createShortcutGen();

  /**
   * Returns a new object of class '<em>Shortcut Lib</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Shortcut Lib</em>'.
   * @generated
   */
  ShortcutLib createShortcutLib();

  /**
   * Returns a new object of class '<em>Short Cut</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Short Cut</em>'.
   * @generated
   */
  ShortCut createShortCut();

  /**
   * Returns a new object of class '<em>Ignored Text</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ignored Text</em>'.
   * @generated
   */
  IgnoredText createIgnoredText();

  /**
   * Returns a new object of class '<em>Url Adress</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Url Adress</em>'.
   * @generated
   */
  UrlAdress createUrlAdress();

  /**
   * Returns a new object of class '<em>Email AT</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Email AT</em>'.
   * @generated
   */
  EmailAT createEmailAT();

  /**
   * Returns a new object of class '<em>Mail Adress</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Mail Adress</em>'.
   * @generated
   */
  MailAdress createMailAdress();

  /**
   * Returns a new object of class '<em>Formula</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Formula</em>'.
   * @generated
   */
  Formula createFormula();

  /**
   * Returns a new object of class '<em>Array</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Array</em>'.
   * @generated
   */
  Array createArray();

  /**
   * Returns a new object of class '<em>New Line</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>New Line</em>'.
   * @generated
   */
  New_Line createNew_Line();

  /**
   * Returns a new object of class '<em>Ext Bracket Sentence</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ext Bracket Sentence</em>'.
   * @generated
   */
  ExtBracketSentence createExtBracketSentence();

  /**
   * Returns a new object of class '<em>EString</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EString</em>'.
   * @generated
   */
  EString createEString();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  NaturalLangPackage getNaturalLangPackage();

} //NaturalLangFactory
