/**
 * generated by Xtext 2.16.0
 */
package de.validas.spedit.naturalLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>New Line</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.validas.spedit.naturalLang.NaturalLangPackage#getNew_Line()
 * @model
 * @generated
 */
public interface New_Line extends AllElements
{
} // New_Line
