/**
 * generated by Xtext 2.16.0
 */
package de.validas.spedit.naturalLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>No NElement X2</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.validas.spedit.naturalLang.NaturalLangPackage#getNoNElementX2()
 * @model
 * @generated
 */
public interface NoNElementX2 extends Elements
{
} // NoNElementX2
