/**
 * generated by Xtext 2.16.0
 */
package de.validas.spedit.naturalLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Table Column Separator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.validas.spedit.naturalLang.TableColumnSeparator#getChar <em>Char</em>}</li>
 * </ul>
 *
 * @see de.validas.spedit.naturalLang.NaturalLangPackage#getTableColumnSeparator()
 * @model
 * @generated
 */
public interface TableColumnSeparator extends TableBorder
{
  /**
   * Returns the value of the '<em><b>Char</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Char</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Char</em>' attribute.
   * @see #setChar(String)
   * @see de.validas.spedit.naturalLang.NaturalLangPackage#getTableColumnSeparator_Char()
   * @model
   * @generated
   */
  String getChar();

  /**
   * Sets the value of the '{@link de.validas.spedit.naturalLang.TableColumnSeparator#getChar <em>Char</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Char</em>' attribute.
   * @see #getChar()
   * @generated
   */
  void setChar(String value);

} // TableColumnSeparator
