/**
 * generated by Xtext 2.16.0
 */
package de.validas.spedit.naturalLang.provider;

import de.validas.spedit.naturalLang.util.NaturalLangAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class NaturalLangItemProviderAdapterFactory extends NaturalLangAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public NaturalLangItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.Model} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ModelItemProvider modelItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.Model}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createModelAdapter() {
		if (modelItemProvider == null) {
			modelItemProvider = new ModelItemProvider(this);
		}

		return modelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.SentenceType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SentenceTypeItemProvider sentenceTypeItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.SentenceType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSentenceTypeAdapter() {
		if (sentenceTypeItemProvider == null) {
			sentenceTypeItemProvider = new SentenceTypeItemProvider(this);
		}

		return sentenceTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.ParagraphBlock} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParagraphBlockItemProvider paragraphBlockItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.ParagraphBlock}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createParagraphBlockAdapter() {
		if (paragraphBlockItemProvider == null) {
			paragraphBlockItemProvider = new ParagraphBlockItemProvider(this);
		}

		return paragraphBlockItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.BlockElement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BlockElementItemProvider blockElementItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.BlockElement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBlockElementAdapter() {
		if (blockElementItemProvider == null) {
			blockElementItemProvider = new BlockElementItemProvider(this);
		}

		return blockElementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.FootNote} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FootNoteItemProvider footNoteItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.FootNote}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFootNoteAdapter() {
		if (footNoteItemProvider == null) {
			footNoteItemProvider = new FootNoteItemProvider(this);
		}

		return footNoteItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.TableLine} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TableLineItemProvider tableLineItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.TableLine}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTableLineAdapter() {
		if (tableLineItemProvider == null) {
			tableLineItemProvider = new TableLineItemProvider(this);
		}

		return tableLineItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.TableBorder} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TableBorderItemProvider tableBorderItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.TableBorder}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTableBorderAdapter() {
		if (tableBorderItemProvider == null) {
			tableBorderItemProvider = new TableBorderItemProvider(this);
		}

		return tableBorderItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.TableRow} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TableRowItemProvider tableRowItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.TableRow}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTableRowAdapter() {
		if (tableRowItemProvider == null) {
			tableRowItemProvider = new TableRowItemProvider(this);
		}

		return tableRowItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.TableColumnSeparator} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TableColumnSeparatorItemProvider tableColumnSeparatorItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.TableColumnSeparator}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTableColumnSeparatorAdapter() {
		if (tableColumnSeparatorItemProvider == null) {
			tableColumnSeparatorItemProvider = new TableColumnSeparatorItemProvider(this);
		}

		return tableColumnSeparatorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.Table} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TableItemProvider tableItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.Table}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTableAdapter() {
		if (tableItemProvider == null) {
			tableItemProvider = new TableItemProvider(this);
		}

		return tableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.LineSentenceChain} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LineSentenceChainItemProvider lineSentenceChainItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.LineSentenceChain}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLineSentenceChainAdapter() {
		if (lineSentenceChainItemProvider == null) {
			lineSentenceChainItemProvider = new LineSentenceChainItemProvider(this);
		}

		return lineSentenceChainItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.SentenceChain} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SentenceChainItemProvider sentenceChainItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.SentenceChain}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSentenceChainAdapter() {
		if (sentenceChainItemProvider == null) {
			sentenceChainItemProvider = new SentenceChainItemProvider(this);
		}

		return sentenceChainItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.SentenceChainX} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SentenceChainXItemProvider sentenceChainXItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.SentenceChainX}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSentenceChainXAdapter() {
		if (sentenceChainXItemProvider == null) {
			sentenceChainXItemProvider = new SentenceChainXItemProvider(this);
		}

		return sentenceChainXItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.Sentence} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SentenceItemProvider sentenceItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.Sentence}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSentenceAdapter() {
		if (sentenceItemProvider == null) {
			sentenceItemProvider = new SentenceItemProvider(this);
		}

		return sentenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.LineSentence} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LineSentenceItemProvider lineSentenceItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.LineSentence}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLineSentenceAdapter() {
		if (lineSentenceItemProvider == null) {
			lineSentenceItemProvider = new LineSentenceItemProvider(this);
		}

		return lineSentenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.FreeSentence} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FreeSentenceItemProvider freeSentenceItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.FreeSentence}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFreeSentenceAdapter() {
		if (freeSentenceItemProvider == null) {
			freeSentenceItemProvider = new FreeSentenceItemProvider(this);
		}

		return freeSentenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.SentenceX} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SentenceXItemProvider sentenceXItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.SentenceX}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSentenceXAdapter() {
		if (sentenceXItemProvider == null) {
			sentenceXItemProvider = new SentenceXItemProvider(this);
		}

		return sentenceXItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.ListSentence} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ListSentenceItemProvider listSentenceItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.ListSentence}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createListSentenceAdapter() {
		if (listSentenceItemProvider == null) {
			listSentenceItemProvider = new ListSentenceItemProvider(this);
		}

		return listSentenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.ChapterSentence} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChapterSentenceItemProvider chapterSentenceItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.ChapterSentence}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChapterSentenceAdapter() {
		if (chapterSentenceItemProvider == null) {
			chapterSentenceItemProvider = new ChapterSentenceItemProvider(this);
		}

		return chapterSentenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.SubSentence} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubSentenceItemProvider subSentenceItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.SubSentence}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubSentenceAdapter() {
		if (subSentenceItemProvider == null) {
			subSentenceItemProvider = new SubSentenceItemProvider(this);
		}

		return subSentenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.TrailSubSentence} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TrailSubSentenceItemProvider trailSubSentenceItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.TrailSubSentence}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTrailSubSentenceAdapter() {
		if (trailSubSentenceItemProvider == null) {
			trailSubSentenceItemProvider = new TrailSubSentenceItemProvider(this);
		}

		return trailSubSentenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.FreeSubSentence} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FreeSubSentenceItemProvider freeSubSentenceItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.FreeSubSentence}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFreeSubSentenceAdapter() {
		if (freeSubSentenceItemProvider == null) {
			freeSubSentenceItemProvider = new FreeSubSentenceItemProvider(this);
		}

		return freeSubSentenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.LineSubSentence} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LineSubSentenceItemProvider lineSubSentenceItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.LineSubSentence}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLineSubSentenceAdapter() {
		if (lineSubSentenceItemProvider == null) {
			lineSubSentenceItemProvider = new LineSubSentenceItemProvider(this);
		}

		return lineSubSentenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.NoNElement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NoNElementItemProvider noNElementItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.NoNElement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNoNElementAdapter() {
		if (noNElementItemProvider == null) {
			noNElementItemProvider = new NoNElementItemProvider(this);
		}

		return noNElementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.Brackets} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BracketsItemProvider bracketsItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.Brackets}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBracketsAdapter() {
		if (bracketsItemProvider == null) {
			bracketsItemProvider = new BracketsItemProvider(this);
		}

		return bracketsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.NoNElementX} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NoNElementXItemProvider noNElementXItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.NoNElementX}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNoNElementXAdapter() {
		if (noNElementXItemProvider == null) {
			noNElementXItemProvider = new NoNElementXItemProvider(this);
		}

		return noNElementXItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.NoNElementX2} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NoNElementX2ItemProvider noNElementX2ItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.NoNElementX2}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNoNElementX2Adapter() {
		if (noNElementX2ItemProvider == null) {
			noNElementX2ItemProvider = new NoNElementX2ItemProvider(this);
		}

		return noNElementX2ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.Elements} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ElementsItemProvider elementsItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.Elements}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createElementsAdapter() {
		if (elementsItemProvider == null) {
			elementsItemProvider = new ElementsItemProvider(this);
		}

		return elementsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.AllElements} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AllElementsItemProvider allElementsItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.AllElements}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAllElementsAdapter() {
		if (allElementsItemProvider == null) {
			allElementsItemProvider = new AllElementsItemProvider(this);
		}

		return allElementsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.BracketSentence} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BracketSentenceItemProvider bracketSentenceItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.BracketSentence}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBracketSentenceAdapter() {
		if (bracketSentenceItemProvider == null) {
			bracketSentenceItemProvider = new BracketSentenceItemProvider(this);
		}

		return bracketSentenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.ExtBracketSentence} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExtBracketSentenceItemProvider extBracketSentenceItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.ExtBracketSentence}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExtBracketSentenceAdapter() {
		if (extBracketSentenceItemProvider == null) {
			extBracketSentenceItemProvider = new ExtBracketSentenceItemProvider(this);
		}

		return extBracketSentenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.EString} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EStringItemProvider eStringItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.EString}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEStringAdapter() {
		if (eStringItemProvider == null) {
			eStringItemProvider = new EStringItemProvider(this);
		}

		return eStringItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.Quote} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected QuoteItemProvider quoteItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.Quote}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createQuoteAdapter() {
		if (quoteItemProvider == null) {
			quoteItemProvider = new QuoteItemProvider(this);
		}

		return quoteItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.Unit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UnitItemProvider unitItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.Unit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUnitAdapter() {
		if (unitItemProvider == null) {
			unitItemProvider = new UnitItemProvider(this);
		}

		return unitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.SimpleUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SimpleUnitItemProvider simpleUnitItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.SimpleUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSimpleUnitAdapter() {
		if (simpleUnitItemProvider == null) {
			simpleUnitItemProvider = new SimpleUnitItemProvider(this);
		}

		return simpleUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.Chapter_Unit_HI} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Chapter_Unit_HIItemProvider chapter_Unit_HIItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.Chapter_Unit_HI}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChapter_Unit_HIAdapter() {
		if (chapter_Unit_HIItemProvider == null) {
			chapter_Unit_HIItemProvider = new Chapter_Unit_HIItemProvider(this);
		}

		return chapter_Unit_HIItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.Chapter_Unit_Low} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Chapter_Unit_LowItemProvider chapter_Unit_LowItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.Chapter_Unit_Low}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChapter_Unit_LowAdapter() {
		if (chapter_Unit_LowItemProvider == null) {
			chapter_Unit_LowItemProvider = new Chapter_Unit_LowItemProvider(this);
		}

		return chapter_Unit_LowItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.HashNumber} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HashNumberItemProvider hashNumberItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.HashNumber}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHashNumberAdapter() {
		if (hashNumberItemProvider == null) {
			hashNumberItemProvider = new HashNumberItemProvider(this);
		}

		return hashNumberItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.ChapterAlpha} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChapterAlphaItemProvider chapterAlphaItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.ChapterAlpha}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChapterAlphaAdapter() {
		if (chapterAlphaItemProvider == null) {
			chapterAlphaItemProvider = new ChapterAlphaItemProvider(this);
		}

		return chapterAlphaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.SymbolsX} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SymbolsXItemProvider symbolsXItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.SymbolsX}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSymbolsXAdapter() {
		if (symbolsXItemProvider == null) {
			symbolsXItemProvider = new SymbolsXItemProvider(this);
		}

		return symbolsXItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.Symbols} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SymbolsItemProvider symbolsItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.Symbols}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSymbolsAdapter() {
		if (symbolsItemProvider == null) {
			symbolsItemProvider = new SymbolsItemProvider(this);
		}

		return symbolsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.ShortcutGen} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ShortcutGenItemProvider shortcutGenItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.ShortcutGen}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createShortcutGenAdapter() {
		if (shortcutGenItemProvider == null) {
			shortcutGenItemProvider = new ShortcutGenItemProvider(this);
		}

		return shortcutGenItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.ShortcutLib} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ShortcutLibItemProvider shortcutLibItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.ShortcutLib}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createShortcutLibAdapter() {
		if (shortcutLibItemProvider == null) {
			shortcutLibItemProvider = new ShortcutLibItemProvider(this);
		}

		return shortcutLibItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.ShortCut} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ShortCutItemProvider shortCutItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.ShortCut}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createShortCutAdapter() {
		if (shortCutItemProvider == null) {
			shortCutItemProvider = new ShortCutItemProvider(this);
		}

		return shortCutItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.IgnoredText} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IgnoredTextItemProvider ignoredTextItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.IgnoredText}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIgnoredTextAdapter() {
		if (ignoredTextItemProvider == null) {
			ignoredTextItemProvider = new IgnoredTextItemProvider(this);
		}

		return ignoredTextItemProvider;
	}


	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.Word} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WordItemProvider wordItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.Word}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWordAdapter() {
		if (wordItemProvider == null) {
			wordItemProvider = new WordItemProvider(this);
		}

		return wordItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.WordShort} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WordShortItemProvider wordShortItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.WordShort}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWordShortAdapter() {
		if (wordShortItemProvider == null) {
			wordShortItemProvider = new WordShortItemProvider(this);
		}

		return wordShortItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.ItWord} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ItWordItemProvider itWordItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.ItWord}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createItWordAdapter() {
		if (itWordItemProvider == null) {
			itWordItemProvider = new ItWordItemProvider(this);
		}

		return itWordItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.UrlAdress} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UrlAdressItemProvider urlAdressItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.UrlAdress}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUrlAdressAdapter() {
		if (urlAdressItemProvider == null) {
			urlAdressItemProvider = new UrlAdressItemProvider(this);
		}

		return urlAdressItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.EmailAT} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EmailATItemProvider emailATItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.EmailAT}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEmailATAdapter() {
		if (emailATItemProvider == null) {
			emailATItemProvider = new EmailATItemProvider(this);
		}

		return emailATItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.MailAdress} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MailAdressItemProvider mailAdressItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.MailAdress}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMailAdressAdapter() {
		if (mailAdressItemProvider == null) {
			mailAdressItemProvider = new MailAdressItemProvider(this);
		}

		return mailAdressItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.Formula} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FormulaItemProvider formulaItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.Formula}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFormulaAdapter() {
		if (formulaItemProvider == null) {
			formulaItemProvider = new FormulaItemProvider(this);
		}

		return formulaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.Array} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArrayItemProvider arrayItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.Array}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArrayAdapter() {
		if (arrayItemProvider == null) {
			arrayItemProvider = new ArrayItemProvider(this);
		}

		return arrayItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.validas.spedit.naturalLang.New_Line} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected New_LineItemProvider new_LineItemProvider;

	/**
	 * This creates an adapter for a {@link de.validas.spedit.naturalLang.New_Line}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNew_LineAdapter() {
		if (new_LineItemProvider == null) {
			new_LineItemProvider = new New_LineItemProvider(this);
		}

		return new_LineItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (modelItemProvider != null) modelItemProvider.dispose();
		if (sentenceTypeItemProvider != null) sentenceTypeItemProvider.dispose();
		if (paragraphBlockItemProvider != null) paragraphBlockItemProvider.dispose();
		if (blockElementItemProvider != null) blockElementItemProvider.dispose();
		if (footNoteItemProvider != null) footNoteItemProvider.dispose();
		if (tableLineItemProvider != null) tableLineItemProvider.dispose();
		if (tableBorderItemProvider != null) tableBorderItemProvider.dispose();
		if (tableRowItemProvider != null) tableRowItemProvider.dispose();
		if (tableColumnSeparatorItemProvider != null) tableColumnSeparatorItemProvider.dispose();
		if (tableItemProvider != null) tableItemProvider.dispose();
		if (lineSentenceChainItemProvider != null) lineSentenceChainItemProvider.dispose();
		if (sentenceChainItemProvider != null) sentenceChainItemProvider.dispose();
		if (sentenceChainXItemProvider != null) sentenceChainXItemProvider.dispose();
		if (sentenceItemProvider != null) sentenceItemProvider.dispose();
		if (lineSentenceItemProvider != null) lineSentenceItemProvider.dispose();
		if (freeSentenceItemProvider != null) freeSentenceItemProvider.dispose();
		if (sentenceXItemProvider != null) sentenceXItemProvider.dispose();
		if (listSentenceItemProvider != null) listSentenceItemProvider.dispose();
		if (chapterSentenceItemProvider != null) chapterSentenceItemProvider.dispose();
		if (subSentenceItemProvider != null) subSentenceItemProvider.dispose();
		if (trailSubSentenceItemProvider != null) trailSubSentenceItemProvider.dispose();
		if (freeSubSentenceItemProvider != null) freeSubSentenceItemProvider.dispose();
		if (lineSubSentenceItemProvider != null) lineSubSentenceItemProvider.dispose();
		if (noNElementItemProvider != null) noNElementItemProvider.dispose();
		if (bracketsItemProvider != null) bracketsItemProvider.dispose();
		if (noNElementXItemProvider != null) noNElementXItemProvider.dispose();
		if (noNElementX2ItemProvider != null) noNElementX2ItemProvider.dispose();
		if (elementsItemProvider != null) elementsItemProvider.dispose();
		if (allElementsItemProvider != null) allElementsItemProvider.dispose();
		if (bracketSentenceItemProvider != null) bracketSentenceItemProvider.dispose();
		if (wordItemProvider != null) wordItemProvider.dispose();
		if (wordShortItemProvider != null) wordShortItemProvider.dispose();
		if (itWordItemProvider != null) itWordItemProvider.dispose();
		if (quoteItemProvider != null) quoteItemProvider.dispose();
		if (unitItemProvider != null) unitItemProvider.dispose();
		if (simpleUnitItemProvider != null) simpleUnitItemProvider.dispose();
		if (chapter_Unit_HIItemProvider != null) chapter_Unit_HIItemProvider.dispose();
		if (chapter_Unit_LowItemProvider != null) chapter_Unit_LowItemProvider.dispose();
		if (hashNumberItemProvider != null) hashNumberItemProvider.dispose();
		if (chapterAlphaItemProvider != null) chapterAlphaItemProvider.dispose();
		if (symbolsXItemProvider != null) symbolsXItemProvider.dispose();
		if (symbolsItemProvider != null) symbolsItemProvider.dispose();
		if (shortcutGenItemProvider != null) shortcutGenItemProvider.dispose();
		if (shortcutLibItemProvider != null) shortcutLibItemProvider.dispose();
		if (shortCutItemProvider != null) shortCutItemProvider.dispose();
		if (ignoredTextItemProvider != null) ignoredTextItemProvider.dispose();
		if (urlAdressItemProvider != null) urlAdressItemProvider.dispose();
		if (emailATItemProvider != null) emailATItemProvider.dispose();
		if (mailAdressItemProvider != null) mailAdressItemProvider.dispose();
		if (formulaItemProvider != null) formulaItemProvider.dispose();
		if (arrayItemProvider != null) arrayItemProvider.dispose();
		if (new_LineItemProvider != null) new_LineItemProvider.dispose();
		if (extBracketSentenceItemProvider != null) extBracketSentenceItemProvider.dispose();
		if (eStringItemProvider != null) eStringItemProvider.dispose();
	}

}
